swagger: '2.0'
info:
  title: Employee API
  description: API Information
  version: '1.0.0'
paths:
  /api/employees/{empId}:
    get:
      tags:
        - Employees
      description: Use to request a specific employee
      parameters:
        - name: empId
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: A successful response
        '400':
          description: Invalid ID supplied
        '404':
          description: Employee not found
  /api/employees:
    get:
      tags:
        - Employees
      description: Use to request all employees
      responses:
        '200':
          description: A successful response
        '404':
          description: Employees not found