swagger: '2.0'
info:
  title: Employee API
  description: API Information
  version: '1.0.0'
paths:
  /api/employees/{empId}:
    get:
      tags:
        - Employees
      description: Use to request a specific employee
      parameters:
        - name: empId
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: A successful response
        '400':
          description: Invalid ID supplied
        '404':
          description: Employee not found
  /api/employees:
    get:
      tags:
        - Employees
      description: Use to request all employees
      responses:
        '200':
          description: A successful response
        '404':
          description: Employees not found
  /api/employees/{empId}/tasks:
    get:
      tags:
        - Tasks
      description: Use to request all employees tasks
      parameters:
        - name: empId
          in: path
          required: true
          type: integer
          format: int32
      responses:
        '200':
          description: A successful response
        '404':
          description: Employees not found
        '400':
          description: Internal server error.
    post:
      tags:
        - Tasks
      description: Use to create a new task
      parameters:
        - name: empId
          in: path
          required: true
          type: integer
          format: int32
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
      responses:
        '200':
          description: A successful response
        '400':
          description: Invalid ID supplied
        '404':
          description: Employee not found